sudo: required
services:
 - docker
 
before_install:
 - docker build -t neoking23/docker-react -f Dockerfile.dev .
 
script:
 - docker run neoking23/docker-react npm run test -- --coverage
 
before_deploy: "echo 'ready?'"

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-102162971088"
 bucket_path: "docker-react"
 on:
  branch:master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"